package xyz.felh.openai.completion.chat;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import xyz.felh.openai.completion.chat.tool.ToolCall;

import java.util.List;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ChatMessage {

    public ChatMessage(ChatMessageRole role, String content) {
        this.role = role;
        this.content = content;
    }

    /**
     * Must be either 'system', 'user', or 'assistant'.<br>
     * You may use {@link ChatMessageRole} enum.
     */
    private ChatMessageRole role;

    /**
     * The contents of message
     */
    private String content;

    /**
     * The tool calls generated by the model, such as function calls.
     */
    private List<ToolCall> toolCalls;

    /**
     * Tool call that this message is responding to.
     */
    private String toolCallId;

}
